import { BarChart3, Boxes, Layers3, LogOut, Menu, PackageCheck, Settings, ShoppingBag, Users, X } from 'lucide-react'
import { useState, type ReactNode } from 'react'
import { Link } from 'react-router-dom'

export type AdminView='overview'|'orders'|'products'|'collections'|'customers'|'settings'
const items:[AdminView,string,typeof BarChart3][]=[['overview','Overview',BarChart3],['orders','Orders',ShoppingBag],['products','Products',Boxes],['collections','Collections',Layers3],['customers','Customers',Users],['settings','Settings',Settings]]
export function AdminShell({view,setView,onExit,preview,children}:{view:AdminView;setView:(v:AdminView)=>void;onExit:()=>void;preview:boolean;children:ReactNode}){
 const [mobile,setMobile]=useState(false)
 const nav=<>{items.map(([id,label,Icon])=><button key={id} onClick={()=>{setView(id);setMobile(false)}} className={`flex w-full items-center gap-3 px-5 py-3.5 text-left text-[10px] uppercase tracking-[.16em] transition ${view===id?'bg-white text-ink':'text-white/55 hover:text-white'}`}><Icon size={16} strokeWidth={1.4}/>{label}</button>)}</>
 return <div className="min-h-screen bg-[#f3f1ed] lg:grid lg:grid-cols-[240px_1fr]"><aside className="hidden min-h-screen bg-ink lg:fixed lg:inset-y-0 lg:left-0 lg:block lg:w-60"><Link to="/" className="block border-b border-white/10 px-6 py-6 font-display text-xl tracking-[.15em] text-white">FÉROCE</Link><div className="px-5 py-4 text-[8px] uppercase tracking-luxury text-white/30">Store command</div><nav>{nav}</nav><div className="absolute inset-x-0 bottom-0 border-t border-white/10 p-5"><p className="mb-3 text-[8px] uppercase tracking-widest text-[#d6b98a]">{preview?'Preview mode':'Verified admin'}</p><button onClick={onExit} className="flex items-center gap-2 text-[9px] uppercase tracking-luxury text-white/55"><LogOut size={14}/> Exit dashboard</button></div></aside><div className="lg:col-start-2"><header className="sticky top-0 z-40 flex h-16 items-center justify-between border-b border-black/10 bg-[#f3f1ed]/95 px-4 backdrop-blur sm:px-7"><button onClick={()=>setMobile(true)} className="p-2 lg:hidden" aria-label="Open admin navigation"><Menu size={20}/></button><div><p className="text-[8px] uppercase tracking-luxury text-black/40">Administration</p><p className="mt-1 font-display text-xl capitalize">{view}</p></div><div className="flex items-center gap-3"><span className="h-2 w-2 rounded-full bg-[#c38c3d]"/><span className="hidden text-[8px] uppercase tracking-widest sm:block">{preview?'Sample data':'Authenticated · live data'}</span><PackageCheck size={17}/></div></header><div className="p-4 sm:p-7 xl:p-10">{children}</div></div>{mobile&&<div className="fixed inset-0 z-50 bg-ink text-white lg:hidden"><div className="flex h-16 items-center justify-between border-b border-white/10 px-5"><span className="font-display tracking-[.15em]">FÉROCE / ADMIN</span><button onClick={()=>setMobile(false)}><X/></button></div><nav className="py-5">{nav}</nav><button onClick={onExit} className="absolute bottom-7 left-5 flex items-center gap-2 text-[9px] uppercase tracking-luxury text-white/55"><LogOut size={14}/> Exit dashboard</button></div>}</div>
}
