import { ArrowRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Newsletter } from '../components/Newsletter'
import { ButtonLink } from '../components/ui/Button'
import { useSeo } from '../lib/seo'

export function AboutPage(){
  useSeo('The FÉROCE story','Meet FÉROCE: the new designer bags for women and men. A black-owned, founder-designed label — high quality, sturdy and luxury, made to be worn every day.')
  return <main className="bg-ivory"><section className="relative min-h-[80svh] overflow-hidden text-white"><img src="/images/hero-campaign-tuned.jpg" alt="FÉROCE brand campaign" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-black/40"/>{/* Measured AA: the uniform veil alone gives the headline 3.45:1 and the eyebrow 2.31:1,
        so a bottom-anchored gradient lifts the copy block to ≥4.5:1. */}<div className="absolute inset-x-0 bottom-0 h-[460px] bg-gradient-to-t from-black/70 to-transparent"/><div className="relative mx-auto flex min-h-[80svh] max-w-7xl items-end px-5 pb-14 sm:px-8 md:pb-20"><div><p className="text-[9px] uppercase tracking-luxury text-white/60">Women + Men · The new designer bags</p><h1 className="mt-5 max-w-4xl font-display text-6xl leading-[.9] sm:text-8xl md:text-9xl">Made to be<br/><em>remembered.</em></h1></div></div></section>
  <section className="px-5 py-20 sm:px-8 md:py-32"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[.7fr_1.3fr]"><p className="text-[9px] uppercase tracking-luxury text-black/45">What FÉROCE means</p><div><p className="font-display text-4xl leading-tight sm:text-5xl md:text-6xl">Féroce means fierce — and that is the point: the new designer bag house, founded and designed by its maker, for her and for him.</p><div className="mt-10 grid gap-7 text-sm leading-7 text-black/55 sm:grid-cols-2"><p>Every silhouette starts with how it will be lived with: how it sits on the shoulder, how it moves through a day, how it holds up to real life. Structured flaps, gold-tone chains, interiors with room for everything.</p><p>Féroce is a black-owned, founder-led label. Bags are designed in-house and produced in limited runs — with one-of-one custom pieces for those who want something no one else has. Ships internationally.</p></div></div></div></section>
  <section className="grid bg-bone lg:grid-cols-2"><div className="min-h-[580px]"><img src="/images/atelier.jpg" alt="FÉROCE gold monogram canvas" className="h-full w-full object-cover"/></div><div className="flex items-center px-6 py-20 sm:px-12 lg:px-20"><div><p className="text-[9px] uppercase tracking-luxury text-black/45">The making</p><h2 className="mt-5 font-display text-5xl leading-none sm:text-6xl">Form follows<br/><em>feeling.</em></h2><p className="mt-7 max-w-lg text-sm leading-7 text-black/55">Every FÉROCE piece is made to be carried every day: denim-textured coated canvas with an all-over gold monogram, gold-tone chain hardware and soft microfiber suede interiors. High quality, sturdy and luxury — made to be seen, and made to last.</p><p className="mt-4 text-[10px] leading-5 text-black/35">Product photography from @ferocefashion_ff — final materials and finish are confirmed with the founder before each order.</p><Link to="/shop" className="group mt-9 inline-flex items-center gap-3 text-[9px] uppercase tracking-luxury">Explore the pieces <ArrowRight size={15} className="transition group-hover:translate-x-1"/></Link></div></div></section>
  <section className="bg-oxblood px-5 py-20 text-white sm:px-8 md:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-14 md:grid-cols-2 md:items-end"><div><p className="text-[9px] uppercase tracking-luxury text-white/45">Founder’s note</p><h2 className="mt-5 font-display text-5xl leading-none sm:text-7xl">A house built<br/>on <em>instinct.</em></h2></div><div><div className="border-l border-white/25 pl-6"><p className="font-display text-2xl leading-relaxed text-white/80">“I started Féroce with one belief: a designer bag should be lived in, not saved. High quality, sturdy, luxury — made to be worn every day and to turn heads while you do. For her, for him, and for everyone bold enough to carry it. This is only the beginning.”</p><p className="mt-5 text-[9px] uppercase tracking-luxury text-white/40">The founder · Féroce — name to be supplied · Drafted from the brand's voice, pending approval</p></div></div></div><div className="mt-20 grid gap-4 sm:grid-cols-3">{[['01','Craft','Designed in-house, built to last.'],['02','For both','For her, for him — never forgotten.'],['03','Presence','Made to be worn — and seen.']].map(([n,t,c])=><div key={n} className="rounded-2xl bg-white/[.08] p-7"><p className="text-[9px] tracking-luxury text-white/45">{n}</p><h3 className="mt-10 font-display text-3xl">{t}</h3><p className="mt-3 text-xs text-white/55">{c}</p></div>)}</div></div></section>
  <section className="px-5 py-20 text-center sm:px-8 md:py-28"><p className="text-[9px] uppercase tracking-luxury text-black/45">The next chapter</p><h2 className="mx-auto mt-5 max-w-3xl font-display text-5xl leading-none sm:text-7xl">Designed now.<br/><em>Defined by what follows.</em></h2><p className="mx-auto mt-6 max-w-lg text-sm leading-7 text-black/50">The house is young and moving fast — new drops, one-of-one commissions and more collections are on the way. Follow the journey at @ferocefashion_ff.</p><ButtonLink to="/contact" className="mt-8">Speak with the house</ButtonLink></section><Newsletter/></main>
}
