import { ArrowDown, ArrowRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { ProductCard } from '../components/ProductCard'
import { SectionHeading } from '../components/SectionHeading'
import { Newsletter } from '../components/Newsletter'
import { ButtonLink } from '../components/ui/Button'
import { useCatalog } from '../context/CatalogContext'
import { contact } from '../data/site'
import { useSeo } from '../lib/seo'

// Shared hero-CTA treatment: equal-weight outline buttons whose shared min-width makes the two
// rectangles identical regardless of label length ('Shop women' is ~23px wider than 'Shop men'
// at natural width, so both take the wider button's width).
const HERO_CTA_CLASS = 'min-w-[150px] border-white text-white hover:bg-white hover:text-ink'

export function HomePage() {
  useSeo('New designer bags for women & men', 'FÉROCE — the new designer bags for women and men. High quality, sturdy and luxury, made to be worn every day and made to be seen.')
  const { products } = useCatalog()
  return <main>
    <section className="relative min-h-[calc(100svh_-_var(--chrome))] overflow-hidden bg-stone-300 text-white">
      <img src="/images/hero-campaign-home.jpg" alt="FÉROCE model wearing the De Ville collection" className="absolute inset-0 h-full w-full object-cover object-center animate-reveal"/>
      {/* Gradient scrim: transparent → rgba(0,0,0,.35) across the left two-thirds, keeping the
          headline and body copy above WCAG AA contrast regardless of the photo's tonal range. */}
      <div className="absolute inset-y-0 left-0 w-2/3 bg-gradient-to-r from-[rgba(0,0,0,0.35)] to-transparent"/>
      <div className="relative mx-auto flex min-h-[calc(100svh_-_var(--chrome))] max-w-[1500px] flex-col justify-end px-5 pb-14 sm:px-8 md:justify-center md:pb-0 lg:px-14">
        {/* Targeted legibility layer behind the copy. The hero photo is real brand photography
            from @ferocefashion_ff (hero-campaign-home.jpg, cropped from the feed) — a dark
            editorial frame with the model in the lower two-thirds, so the gradient stays light.
            The image's left third measures ~50 mean brightness; the 0.50/0.50/0.34 stops hold
            ≥4.75:1 across 360px–1920px; re-verify if the hero photo changes. */}
        <div className="absolute inset-y-0 left-0 w-full max-w-xl bg-gradient-to-r from-[rgba(0,0,0,0.50)] via-[rgba(0,0,0,0.50)] to-[rgba(0,0,0,0.34)]"/>
        <div className="relative max-w-xl animate-fade-up"><p className="text-[10px] uppercase tracking-[.3em] text-white/75">The new designer bags · Women + Men</p><h1 className="mt-5 font-display text-6xl leading-[.88] sm:text-7xl md:text-[92px]">Luxury<br/>with <em>instinct.</em></h1><p className="mt-6 max-w-md text-sm leading-6 text-white md:text-base">The new designer bags for women and men. High quality, sturdy and luxury — worn every day, made to be seen.</p><div className="mt-8 flex flex-wrap gap-3">{/* Equal-weight CTAs — both outline by design: /women and /men are equivalent-value routes with no primary/secondary merchandising hierarchy, so the buttons must not imply one line outranks the other; the shared HERO_CTA_CLASS min-width keeps the two rectangles identical. */}<ButtonLink to="/women" variant="outline" className={HERO_CTA_CLASS}>Shop women</ButtonLink><ButtonLink to="/men" variant="outline" className={HERO_CTA_CLASS}>Shop men</ButtonLink></div></div>
        {/* Scroll cue: pinned to the content margin (matches the section's own px-5/sm:px-8/lg:px-14)
            so it can never touch or clip at the viewport's right edge on any width. */}
        <button onClick={() => document.getElementById('house-collections')?.scrollIntoView({ behavior: 'smooth', block: 'start' })} className="absolute bottom-6 right-5 hidden cursor-pointer items-center gap-3 whitespace-nowrap text-[10px] uppercase tracking-[.16em] md:bottom-8 md:flex md:right-8 lg:right-14" aria-label="Explore the house — scroll to the collections"><ArrowDown size={15} className="animate-bounce-soft"/> Explore the house</button>
      </div>
    </section>

    {/* The collections — light editorial tiles, rounded like the reference store. */}
    <section id="house-collections" className="bg-ivory px-5 py-20 sm:px-8 md:py-28">
      <div className="mx-auto max-w-7xl"><SectionHeading eyebrow="The collections" aside={<Link to="/collections" className="group flex items-center gap-3 text-[10px] uppercase tracking-luxury">View all <ArrowRight size={16} className="transition group-hover:translate-x-1"/></Link>}>Two worlds.<br/><em>One instinct.</em></SectionHeading>
        <div className="grid gap-4 md:grid-cols-2 md:gap-6">
          <Link to="/women" className="group relative aspect-[4/5] overflow-hidden rounded-2xl ring-1 ring-black/[.06]"><img src="/images/women-campaign.jpg" alt="Women's collection campaign" className="h-full w-full object-cover transition duration-1000 group-hover:scale-[1.025]"/><div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent"/><div className="absolute bottom-0 left-0 right-0 flex items-end justify-between p-6 text-white sm:p-8"><div><p className="text-[9px] uppercase tracking-luxury text-white/65">Collection 01</p><h3 className="mt-2 font-display text-4xl sm:text-5xl">For Her</h3><p className="mt-2 text-xs text-white/70">Poise, reimagined.</p></div><span className="grid h-11 w-11 place-items-center rounded-full bg-white text-ink transition group-hover:bg-ink group-hover:text-white"><ArrowRight size={17}/></span></div></Link>
          <Link to="/men" className="group relative aspect-[4/5] overflow-hidden rounded-2xl ring-1 ring-black/[.06]"><img src="/images/men-campaign.jpg" alt="Men's collection campaign" className="h-full w-full object-cover transition duration-1000 group-hover:scale-[1.025]"/><div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent"/><div className="absolute bottom-0 left-0 right-0 flex items-end justify-between p-6 text-white sm:p-8"><div><p className="text-[9px] uppercase tracking-luxury text-white/65">Collection 02</p><h3 className="mt-2 font-display text-4xl sm:text-5xl">For Him</h3><p className="mt-2 text-xs text-white/70">Utility, with intention.</p></div><span className="grid h-11 w-11 place-items-center rounded-full bg-white text-ink transition group-hover:bg-ink group-hover:text-white"><ArrowRight size={17}/></span></div></Link>
        </div>
        {/* Merchandising band — light cards, reference-style (New arrivals / Best sellers / Pre-order). */}
        <div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 md:mt-6 md:gap-6">{[
          ['New arrivals','First impressions','/shop?badge=NEW','/images/product-rouge.jpg','bg-blush'],['Best sellers','The icons','/shop?badge=BEST+SELLER','/images/product-noir.jpg','bg-lilac'],['Pre-order','Before everyone','/shop?badge=PRE-ORDER','/images/product-mini.jpg','bg-mint']
        ].map(([title,sub,to,img,tint],i)=><Link key={title} to={to} className={`group relative overflow-hidden rounded-2xl ${tint} ${i===2?'col-span-2 aspect-[2/1] sm:col-span-1 sm:aspect-[4/5]':'aspect-[4/5]'}`}><img src={img} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/50 to-transparent p-4 pt-14 text-white sm:p-6 sm:pt-20"><p className="font-display text-2xl md:text-3xl">{title}</p><p className="mt-1 text-[9px] uppercase tracking-[.16em] text-white/70">{sub}</p></div></Link>)}</div>
      </div>
    </section>

    {/* Featured collections — the reference's category-tile pattern: rounded image, overlay, Shop Now. */}
    <section className="bg-bone px-5 py-20 sm:px-8 md:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Featured collections" aside={<ButtonLink to="/shop" variant="text">Shop all pieces</ButtonLink>}>Find your<br/><em>silhouette.</em></SectionHeading>
      <div className="mt-12 grid grid-cols-2 gap-4 sm:gap-5 lg:grid-cols-4">{[['Handbags','The De Ville line','/shop','/images/product-noir.jpg'],['For Her','Poise, reimagined','/women','/images/women-campaign.jpg'],['For Him','Utility, with intention','/men','/images/men-campaign.jpg'],['Travel','Concise journeys','/shop?category=Travel','/images/product-weekender.jpg']].map(([title,sub,to,img])=><Link key={title} to={to} className="group relative aspect-[4/5] overflow-hidden rounded-2xl ring-1 ring-black/[.06]"><img src={img} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/65 to-transparent p-5 pt-16 text-white sm:p-6"><p className="font-display text-2xl sm:text-3xl">{title}</p><p className="mt-1 text-[9px] uppercase tracking-[.16em] text-white/70">{sub}</p><span className="mt-4 inline-flex items-center gap-2 border-b-2 border-white pb-1 text-[9px] font-semibold uppercase tracking-luxury transition group-hover:border-gold group-hover:text-gold">Shop now <ArrowRight size={13}/></span></div></Link>)}</div>
    </div></section>

    <section className="bg-ivory px-5 py-20 sm:px-8 md:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Curated now" aside={<ButtonLink to="/shop" variant="text">Shop all pieces</ButtonLink>}>Objects of<br/><em>desire.</em></SectionHeading><div className="grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-4 md:gap-x-5">{products.slice(0,4).map((p,i)=><ProductCard key={p.id} product={p} priority={i<2}/>)}</div></div></section>

    {/* Instagram social proof — the reference's "loved by followers" band, on a light surface. */}
    <section className="bg-paper px-5 py-20 sm:px-8 md:py-28"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-7 md:flex-row md:items-end md:justify-between"><div><p className="text-[9px] uppercase tracking-luxury text-black/40">The feed</p><h2 className="mt-4 font-display text-5xl font-semibold leading-none sm:text-6xl">Loved on<br/><em>the feed.</em></h2><p className="mt-5 max-w-md text-sm leading-6 text-black/55">Styled, worn and spotted — the house as it happens. Follow the journey at @ferocefashion_ff.</p></div><a href={contact.instagram} target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 rounded-full border border-black/15 px-6 py-4 text-[10px] font-semibold uppercase tracking-luxury transition hover:bg-ink hover:text-white">Follow @ferocefashion_ff <ArrowRight size={15}/></a></div><div className="mt-12 grid grid-cols-3 gap-2 sm:grid-cols-6 sm:gap-3">{['/images/product-noir.jpg','/images/women-campaign.jpg','/images/product-rouge.jpg','/images/naji-campaign.jpg','/images/men-campaign.jpg','/images/product-sable.jpg'].map(src=><a key={src} href={contact.instagram} target="_blank" rel="noreferrer" className="group relative aspect-square overflow-hidden rounded-xl"><img src={src} alt="FÉROCE on Instagram" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><span className="absolute inset-0 transition group-hover:bg-black/15"/></a>)}</div><p className="mt-5 text-[9px] leading-4 text-black/35">Feed photography from @ferocefashion_ff — confirm usage rights with the client.</p></div></section>

    {/* Customer love — real mentions taken from the brand's own posts (no fabricated reviews). */}
    <section className="bg-ivory px-5 py-20 sm:px-8 md:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Spotted in the wild" aside={<Link to="/collections" className="group flex items-center gap-3 text-[10px] uppercase tracking-luxury">Browse the collections <ArrowRight size={16} className="transition group-hover:translate-x-1"/></Link>}>Worn by<br/><em>the house.</em></SectionHeading>
      <div className="mt-12 grid gap-4 md:grid-cols-3 md:gap-6">{[['“Golden Fur, Black Bobby shiney, Red Satin interior — the Naji, spotted out in the wild.”','@iambiglex__','/images/product-mini.jpg'],['“Real footage of customers spotted in our Red Maroon Naji Collection — a special gift for special women.”','Red Maroon Naji','/images/naji-campaign.jpg'],['“Trying on our blue denim with gold monogram print purse — you can wear this bag with almost anything.”','De Ville denim','/images/product-homme.jpg']].map(([quote,by,img])=><figure key={by} className="rounded-2xl border border-black/[.06] bg-paper p-7 shadow-[0_14px_36px_-24px_rgba(20,18,16,.18)]"><img src={img} alt="" className="h-20 w-20 rounded-full object-cover ring-1 ring-black/10"/><blockquote className="mt-6 font-display text-xl leading-relaxed text-black/80">{quote}</blockquote><figcaption className="mt-5 text-[9px] font-semibold uppercase tracking-luxury text-black/45">— {by}</figcaption></figure>)}</div>
      <p className="mt-8 text-[9px] leading-4 text-black/35">Mentions as shared on the brand's feed (@ferocefashion_ff).</p>
    </div></section>

    {/* The philosophy — light split, keeping the brand's voice. */}
    <section className="bg-bone lg:grid lg:grid-cols-2"><div className="relative min-h-[460px] lg:min-h-full"><img src="/images/atelier.jpg" alt="FÉROCE gold monogram canvas detail" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-black/10"/><span className="absolute bottom-5 left-5 rounded-full bg-ink/70 px-4 py-2 text-[8px] uppercase tracking-luxury text-white/80 backdrop-blur">The making of presence</span></div><div className="flex items-center px-6 py-20 sm:px-12 lg:px-20"><div className="max-w-xl"><p className="text-[9px] font-semibold uppercase tracking-luxury text-black/45">Our philosophy</p><h2 className="mt-6 font-display text-5xl font-semibold leading-[.95] sm:text-6xl">Not an accessory.<br/><em>An attitude.</em></h2><p className="mt-8 max-w-lg text-sm leading-7 text-black/65">Every piece is designed in-house and made to be lived with: sturdy, high quality and luxury — from the gold-monogram De Ville to the soft-fur Naji. A bag should move with you, hold up to real life and still turn heads.</p><p className="mt-4 text-[10px] leading-5 text-black/40">A black-owned, founder-designed label · Ships internationally</p><ButtonLink to="/about" className="mt-9">Discover our story</ButtonLink></div></div></section>

    {/* Want to learn more? — the reference's service columns, linking the real info pages. */}
    <section className="bg-ivory px-5 py-20 sm:px-8 md:py-28"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Client services">Want to<br/><em>learn more?</em></SectionHeading>
      <div className="mt-12 grid gap-4 md:grid-cols-3 md:gap-6">{[['/images/atelier.jpg','Care guide','How to keep the De Ville canvas and the Naji fur beautiful.','/care-guide'],['/images/hero-campaign-home.jpg','Shipping & returns','How an order travels from the house to you — and what happens if a piece isn’t the one.','/shipping-returns'],['/images/product-noir.jpg','Speak with the house','Questions, commissions and press — the house answers.','/contact']].map(([img,title,sub,to])=><Link key={title} to={to} className="group overflow-hidden rounded-2xl border border-black/[.06] bg-paper transition duration-300 hover:shadow-[0_18px_40px_-18px_rgba(20,18,16,.25)]"><div className="aspect-[8/10] overflow-hidden"><img src={img} alt="" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-6"><h3 className="font-display text-xl font-semibold uppercase tracking-wide">{title}</h3><p className="mt-2 text-sm leading-6 text-black/55">{sub}</p><span className="mt-4 inline-flex items-center gap-2 border-b-2 border-black pb-1 text-[9px] font-semibold uppercase tracking-luxury transition group-hover:border-oxblood group-hover:text-oxblood">Learn more <ArrowRight size={13}/></span></div></Link>)}</div>
    </div></section>

    <section className="relative min-h-[78svh] overflow-hidden"><img src="/images/hero-campaign-home.jpg" alt="FÉROCE seasonal editorial campaign" className="absolute inset-0 h-full w-full scale-110 object-cover object-center"/><div className="absolute inset-0 bg-black/35"/>{/* Measured AA: at 0.35 the centered headline is 2.94:1 and the eyebrow 2.19:1, so a
        centered legibility band lifts the copy block to ≥4.5:1 while the image edges stay bright. */}<div className="absolute inset-x-0 top-1/2 h-[380px] -translate-y-1/2 bg-gradient-to-r from-transparent via-black/55 to-transparent"/><div className="relative mx-auto flex min-h-[78svh] max-w-7xl items-center justify-center px-6 text-center text-white"><div><p className="text-[10px] uppercase tracking-[.3em] text-white/65">The collections · De Ville &amp; Naji</p><h2 className="mt-5 font-display text-6xl leading-[.9] sm:text-8xl md:text-9xl">Own the<br/><em>entrance.</em></h2><ButtonLink to="/collections" variant="light" className="mt-9">Explore the collections</ButtonLink></div></div></section>
    <Newsletter/>
  </main>
}
